# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:44:38+00:00

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel, Field, RootModel


class Action1Enum(Enum):
    trial = 'trial'
    plan = 'plan'
    subscribe = 'subscribe'


class Action1(RootModel[Optional[Action1Enum]]):
    root: Optional[Action1Enum] = Field(
        None,
        description='Action to enable targets:\n* null - no action required\n* trial - start a trial\n* plan - select a plan to subscribe\n* subscribe - add target to subscribed plan\n',
    )


class Action(BaseModel):
    action: Optional[Action1] = Field(
        None,
        description='Action to enable targets:\n* null - no action required\n* trial - start a trial\n* plan - select a plan to subscribe\n* subscribe - add target to subscribed plan\n',
    )


class Action3(Enum):
    edit = 'edit'
    delete = 'delete'
    trial = 'trial'
    plan = 'plan'
    subscribe = 'subscribe'
    unsubscribe = 'unsubscribe'
    archive = 'archive'
    activate = 'activate'


class Action2(BaseModel):
    action: Optional[Action3] = Field(
        None,
        description='Actions are:\n* edit - edit target\n* delete - delete target\n* trial - start a trial with this target\n* plan - select a subscipition plan with this target\n* subscribe - add target to subscribed plan\n* unsubscribe - remove target from subscription\n* archive - archive target\n* activate - unarchive target\n',
    )
    label: Optional[str] = Field(None, description='Label or the action')


class Actions(RootModel[List[Action2]]):
    root: List[Action2]


class Change(Enum):
    created = 'created'
    comment = 'comment'
    found = 'found'
    changed = 'changed'


class Cookie(BaseModel):
    name: Optional[str] = Field(None, description='Cookie name.', examples=['cookie_1'])
    value: Optional[str] = Field(
        None, description='Cookie value.', examples=['cookie_value']
    )


class Cookies(RootModel[List[Cookie]]):
    root: List[Cookie] = Field(..., description='Custom cookies name/value pairs')


class Definition(BaseModel):
    desc: Optional[str] = Field(
        None, description='Vulnerability definition description.'
    )
    id: Optional[str] = Field(None, description='Vulnerability definition id.')
    name: Optional[str] = Field(None, description='Vulnerability definition name.')


class FindingBulkIds(BaseModel):
    ids: List[str] = Field(..., description='Array of finding ids')


class FormLoginItem(BaseModel):
    name: Optional[str] = Field(
        None, description='Field name/id', examples=['username']
    )
    value: Optional[str] = Field(None, description='Field input', examples=['probely'])


class FormLogin(RootModel[List[FormLoginItem]]):
    root: List[FormLoginItem] = Field(
        ..., description='Form login field name, field input pairs'
    )


class Header(BaseModel):
    name: Optional[str] = Field(
        None, description='Header name.', examples=['X-Custom-Header']
    )
    value: Optional[str] = Field(None, description='Header value.', examples=['XXXXX'])


class Headers(RootModel[List[Header]]):
    root: List[Header] = Field(..., description='Custom headers name value pairs')


class IntegrationFields(BaseModel):
    heroku: Optional[bool] = None
    jira_cloud: Optional[bool] = None
    jira_server: Optional[bool] = None
    slack: Optional[bool] = None


class Integrations(BaseModel):
    available: Optional[IntegrationFields] = None
    installed: Optional[IntegrationFields] = None


class Discount(BaseModel):
    amount: Optional[int] = Field(None, description='Discounted amount in cents')
    description: Optional[str] = Field(None, description='Discount description')


class LineItem(BaseModel):
    amount: Optional[int] = Field(None, description='Total amount in cents')
    description: Optional[str] = Field(None, description='Charge description')
    discount_amount: Optional[int] = Field(None, description='Discount amount in cents')
    quantity: Optional[int] = Field(None, description='Units charged')
    tax_amount: Optional[int] = Field(None, description='Tax amount in cents')
    unit_amount: Optional[int] = Field(None, description='Price per unit in cents')


class Tax(BaseModel):
    tax_amount: Optional[int] = Field(None, description='Amount of tax in cents')
    tax_name: Optional[str] = Field(None, description='Name of applied tax')
    tax_rate: Optional[float] = Field(None, description='Tax rate')


class JiraIssuePriority(BaseModel):
    id: Optional[str] = Field(
        None, description='Jira issue priority id', examples=['3']
    )
    name: Optional[str] = Field(
        None, description='Jira issue priority name', examples=['Medium']
    )


class JiraIssueStatus(BaseModel):
    id: Optional[str] = Field(
        None, description='Jira issue status id', examples=['10003']
    )
    name: Optional[str] = Field(
        None, description='Jira issue status name', examples=['Backlog']
    )


class JiraIssueType(BaseModel):
    id: Optional[str] = Field(
        None, description='Jira issue type id', examples=['10003']
    )
    name: Optional[str] = Field(
        None, description='Jira issue type name', examples=['Story']
    )


class JiraProject(BaseModel):
    id: Optional[str] = Field(None, description='Jira project id', examples=['10001'])
    name: Optional[str] = Field(
        None, description='Jira project name', examples=['Project']
    )


class Request(BaseModel):
    request: Optional[str] = None
    response: Optional[str] = None


class Requests(RootModel[List[Request]]):
    root: List[Request] = Field(
        ..., description='Request response pairs that produced the finding'
    )


class State(Enum):
    started = 'started'
    ended = 'ended'


class Status(BaseModel):
    field_0: Optional[int] = Field(
        None, alias='0', description='Number of crawled URLs'
    )
    field_1: Optional[int] = Field(
        None, alias='1', description='Total number of URLs in the queue'
    )


class Crawler(BaseModel):
    error: Optional[List[str]] = Field(
        None, description='List of possible errors from the crawler'
    )
    state: Optional[State] = Field(None, description='The current state of the crawler')
    status: Optional[Status] = Field(
        None,
        description='The number of crawled URLs and total number of URLs in the queue',
    )
    warning: Optional[List[str]] = Field(
        None, description='List of possible warnings from the crawler'
    )


class Fingerprinter(BaseModel):
    count: Optional[int] = Field(
        None, description='The number of detected frameworks/software on the target'
    )
    error: Optional[List[str]] = Field(
        None, description='List of possible errors from the fingerprinter'
    )
    state: Optional[State] = Field(
        None, description='The current state of the fingerprinter'
    )
    warning: Optional[List[str]] = Field(
        None, description='List of possible warnings from the fingerprinter'
    )


class Status1(BaseModel):
    field_0: Optional[int] = Field(
        None, alias='0', description='Number of completed tasks'
    )
    field_1: Optional[int] = Field(
        None, alias='1', description='Total number of tasks in the queue'
    )


class Scanner(BaseModel):
    error: Optional[List[str]] = Field(
        None, description='List of possible errors from the scanner'
    )
    state: Optional[State] = Field(None, description='The current state of the scanner')
    status: Optional[Status1] = Field(
        None,
        description='The number of scanner tasks completed and total number of tasks in the queue',
    )
    warning: Optional[List[str]] = Field(
        None, description='List of possible warnings from the scanner'
    )


class Slack(BaseModel):
    notify_finding_fixed: Optional[bool] = Field(
        False, description='Notify of fixed findings.'
    )
    notify_high_findings: Optional[bool] = Field(
        False, description='Notify of new high severity findings.'
    )
    notify_low_findings: Optional[bool] = Field(
        False, description='Notify of new low severity findings.'
    )
    notify_medium_findings: Optional[bool] = Field(
        False, description='Notify of new medium severity findings.'
    )
    notify_scan_completed: Optional[bool] = Field(
        False, description='Notify of completed scans.'
    )
    notify_scan_started: Optional[bool] = Field(
        False, description='Notify of started scans.'
    )
    webhook_url: Optional[str] = Field(
        '', description='Slack notification webhook url.'
    )


class Whitelist(RootModel[List[str]]):
    root: List[str]


class AccountAutoCollection(Enum):
    on = 'on'
    off = 'off'


class AccountBalance(RootModel[int]):
    root: int = Field(..., description='Account balance in cents', examples=[0])


class AccountNextBillingAt(RootModel[date]):
    root: date = Field(
        ...,
        description='Date of next billing',
        examples=['2018-01-31T16:32:17.238553Z'],
    )


class AccountPlanId(RootModel[str]):
    root: str = Field(..., description='Current plan id', examples=['jMXUw-BE_2vd'])


class AccountStatus(Enum):
    active = 'active'
    trial_ended = 'trial_ended'
    canceled = 'canceled'


class Address(RootModel[str]):
    root: str = Field(..., description='Address')


class BasicAuthUsername(RootModel[str]):
    root: str = Field(..., description='Username', examples=['probely'])


class BillingPeriod(RootModel[str]):
    root: str = Field(
        ..., description='Number of of period unit between charges', examples=[1]
    )


class BillingPeriodUnit(Enum):
    month = 'month'
    year = 'year'


class Changed(RootModel[datetime]):
    root: datetime = Field(
        ...,
        description='Date time of the last change',
        examples=['2018-01-31T16:32:17.238553Z'],
    )


class City(RootModel[str]):
    root: str = Field(..., description='City', examples=['Munich'])


class ConnectedTarget(RootModel[str]):
    root: str = Field(
        ..., description='Id of the connected target in a multi-environment targets.\n'
    )


class Country(RootModel[str]):
    root: str = Field(..., description='ISO 3166 alpha-2 country code', examples=['DE'])


class Coupons(RootModel[List[str]]):
    root: List[str] = Field(..., description='Coupon ids')


class Created(RootModel[datetime]):
    root: datetime = Field(
        ...,
        description='Date time of creation',
        examples=['2018-01-31T16:32:17.238553Z'],
    )


class CurrencyCode(RootModel[str]):
    root: str = Field(..., description='3 letter currency code', examples=['EUR'])


class Desc(RootModel[str]):
    root: str = Field(
        ...,
        description='Custom description for the resource',
        examples=['Object description'],
    )


class Email(RootModel[str]):
    root: str = Field(..., description='Contact email')


class EmailToken(RootModel[str]):
    root: str = Field(
        ...,
        description='Reset token received in the user email',
        examples=[
            'KJUUCY2VIVEHO5KJGVHQ====-PJZXGNKSGNQVSODFPJGQ====-GYZDKOI=-8065bfbf8a0192774f3f/'
        ],
    )


class Enabled(RootModel[bool]):
    root: bool = Field(
        ...,
        description="Certain operations (e.g. changing a target's `type`) may require going through billing. Until the change is reverted or the billing is settled.\n",
    )


class Environment(Enum):
    testing = 'testing'
    production = 'production'


class EventObjectType(Enum):
    user = 'user'
    target = 'target'
    scan = 'scan'
    finding = 'finding'


class EventOccurredAt(RootModel[datetime]):
    root: datetime = Field(
        ...,
        description='Date time of when the event occurred',
        examples=['2018-01-31T16:32:17.238553Z'],
    )


class EventType(Enum):
    user_created = 'user_created'
    user_deleted = 'user_deleted'
    target_created = 'target_created'
    target_deleted = 'target_deleted'
    target_verified = 'target_verified'
    target_verification_failed = 'target_verification_failed'
    scan_started = 'scan_started'
    scan_canceled = 'scan_canceled'
    scan_completed = 'scan_completed'
    scan_failed = 'scan_failed'
    finding_detected = 'finding_detected'
    finding_fixed = 'finding_fixed'


class FindingCVSSScore(RootModel[float]):
    root: float = Field(..., description='CVSS score', examples=[6.5])


class FindingCVSSVector(RootModel[str]):
    root: str = Field(
        ...,
        description='CVSS vector',
        examples=['CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N'],
    )


class FindingInsertionPoint(Enum):
    cookie = 'cookie'
    header = 'header'
    parameter = 'parameter'
    arbitrary_url_param_name = 'arbitrary_url_param_name'
    url_path_folder = 'url_path_folder'
    field_ = ''


class FindingSeverity(Enum):
    field_10 = 10
    field_20 = 20
    field_30 = 30


class FindingState(Enum):
    notfixed = 'notfixed'
    invalid = 'invalid'
    accepted = 'accepted'
    fixed = 'fixed'


class FirstName(RootModel[str]):
    root: str = Field(..., description='First name')


class FormLoginCheckPattern(RootModel[str]):
    root: str = Field(
        ..., description='Pattern to check successful authentication (not used)'
    )


class FormLoginUrl(RootModel[str]):
    root: str = Field(
        ..., description='URL for the form login', examples=['https://app.probely.com/']
    )


class FrameworkNames(RootModel[str]):
    root: str = Field(..., description='Framework/Software name.', examples=['nginx'])


class FreeTargetQuantity(RootModel[int]):
    root: int = Field(..., description='Number of free targets', examples=[3])


class HasBasicAuth(RootModel[bool]):
    root: bool = Field(
        ..., description='Use basic authentication in scan', examples=[True]
    )


class HasFormLogin(RootModel[bool]):
    root: bool = Field(
        ..., description='Does the resource use form login', examples=[True]
    )


class HasUsedTrial(RootModel[bool]):
    root: bool = Field(
        ..., description="Has account used up it's trial", examples=[True]
    )


class Host(RootModel[str]):
    root: str = Field(..., description='Fully qualified hostname')


class Id(RootModel[str]):
    root: str = Field(..., description='Object id.', examples=['jMXUw-BE_2vd'])


class Include(RootModel[bool]):
    root: bool = Field(..., description='Use this asset in scans.')


class JiraAllowJira(RootModel[bool]):
    root: bool = Field(..., description='Is this target allowed Jira integration.')


class JiraAutoSync(RootModel[bool]):
    root: bool = Field(
        ..., description='Automatically synchronise all findings to Jira issues.'
    )


class JiraIssueId(RootModel[str]):
    root: str = Field(..., description='Jira issue id connected to this finding')


class JiraIssueTypeId(RootModel[str]):
    root: str = Field(..., description='Id of the issue type to be created in Jira.')


class JiraPriorityMapping(BaseModel):
    field_10: Optional[str] = Field(
        None,
        alias='10',
        description='Id of the Jira priority that low severity findings should be mapped to.',
    )
    field_20: Optional[str] = Field(
        None,
        alias='20',
        description='Id of the Jira priority that medium severity findings should be mapped to.',
    )
    field_30: Optional[str] = Field(
        None,
        alias='30',
        description='Id of the Jira status that high severity findings should be mapped to.',
    )


class JiraProjectId(RootModel[str]):
    root: str = Field(
        ...,
        description='Id of the Jira project where issues for this target will be created.',
    )


class JiraSelectiveSync(RootModel[bool]):
    root: bool = Field(..., description='Selective sync active for this finding.')


class JiraStatusMapping(BaseModel):
    accepted: Optional[str] = Field(
        None,
        description='Id of the Jira status that `accepted` findings should be mapped to.',
    )
    fixed: Optional[str] = Field(
        None,
        description='Id of the Jira status that `fixed` findings should be mapped to.',
    )
    invalid: Optional[str] = Field(
        None,
        description='Id of the Jira status that `invalid` findings should be mapped to.',
    )
    notfixed: Optional[str] = Field(
        None,
        description='Id of the Jira status that `notfixed` findings should be mapped to.',
    )


class LastName(RootModel[str]):
    root: str = Field(..., description='Last name')


class Method(Enum):
    GET = 'GET'
    OPTIONS = 'OPTIONS'
    POST = 'POST'
    PUT = 'PUT'
    PATCH = 'PATCH'
    DELETE = 'DELETE'
    HEAD = 'HEAD'


class Name(RootModel[str]):
    root: str = Field(
        ..., description='Custom name for the resource', examples=['Object name']
    )


class PaginationCount(RootModel[int]):
    root: int = Field(
        ..., description='Number of objects in the response.', examples=[6]
    )


class PaginationLength(RootModel[int]):
    root: int = Field(..., description='Number of objects per page.', examples=[10])


class PaginationPage(RootModel[int]):
    root: int = Field(..., description='Current page.', examples=[1])


class PaginationPageTotal(RootModel[int]):
    root: int = Field(..., description='Number of pages.', examples=[1])


class Password(RootModel[str]):
    root: str = Field(..., examples=['dolphins'])


class PlanAllowedScanProfiles(RootModel[List[str]]):
    root: List[str] = Field(
        ..., description='List of scan profiles allowed by the plan'
    )


class PlanChargeModel(Enum):
    per_unit = 'per_unit'
    flat_fee = 'flat_fee'


class PlanIsTrial(RootModel[bool]):
    root: bool = Field(..., description='Is this a trial plan', examples=[False])


class PlanTargetQuantity(RootModel[int]):
    root: int = Field(..., description='Number of subscribed targets', examples=[3])


class PoolSize(RootModel[int]):
    root: int = Field(
        ...,
        description='Maximum number of subscribed target for pool plans',
        examples=[5],
    )


class Price(RootModel[int]):
    root: int = Field(..., description='Price in cents', examples=[5000])


class Recurrence(Enum):
    d = 'd'
    w = 'w'
    m = 'm'
    q = 'q'
    field_ = ''


class RegistrationNumber(RootModel[str]):
    root: str = Field(..., description='Company registration number')


class ReportType(Enum):
    default = 'default'
    owasp = 'owasp'
    pci = 'pci'


class ScanCompleted(RootModel[datetime]):
    root: datetime = Field(
        ...,
        description='Date time of scan completion',
        examples=['2018-01-31T16:32:17.238553Z'],
    )


class ScanDateTime(RootModel[datetime]):
    root: datetime = Field(..., description='Date time of next scan')


class ScanProfile(Enum):
    safe = 'safe'
    normal = 'normal'
    full = 'full'
    lightning = 'lightning'


class ScanStarted(RootModel[datetime]):
    root: datetime = Field(
        ...,
        description='Date time of scan start',
        examples=['2018-01-31T16:32:17.238553Z'],
    )


class ScanStatus(Enum):
    queued = 'queued'
    started = 'started'
    under_review = 'under_review'
    completed = 'completed'
    completed_with_errors = 'completed_with_errors'
    failed = 'failed'
    canceled = 'canceled'
    canceling = 'canceling'


class SiteHost(RootModel[str]):
    root: str = Field(..., description='Site host', examples=['app.probely.com'])


class SiteUrl(RootModel[str]):
    root: str = Field(
        ...,
        description='Site URL, it should include the path if the site is not located at the root. This URL can only be set once.\n',
        examples=['https://app.probely.com'],
    )


class TargetIds(RootModel[List[Id]]):
    root: List[Id]


class TargetType(Enum):
    free = 'free'
    single = 'single'
    multi = 'multi'


class Token(RootModel[str]):
    root: str = Field(
        ...,
        description='Authentication token',
        examples=[
            'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJKR3ZRSTkzSTJhc0oiLCJ0ZW5hbnQiOiJwcm9iZWx5IiwidXNlcm5hbWUiOiJxd2VAZGVmbnVsbC5ldSJ9.7KtUn-Oy8aevOCv2lAnDroAJojLXmm7m2A4CX5cjwAk'
        ],
    )


class TokenBody(RootModel[str]):
    root: str = Field(
        ...,
        description='Authentication token',
        examples=[
            'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJKR3ZRSTkzSTJhc0oiLCJ0ZW5hbnQiOiJwcm9iZWx5IiwidXNlcm5hbWUiOiJxd2VAZGVmbnVsbC5ldSJ9.7KtUn-Oy8aevOCv2lAnDroAJojLXmm7m2A4CX5cjwAk'
        ],
    )


class TrialEnd(RootModel[datetime]):
    root: datetime = Field(
        ...,
        description='Trial termination date',
        examples=['2018-01-31T16:32:52.226652Z'],
    )


class Ttl(RootModel[int]):
    root: int = Field(
        ..., description='Token time to live in seconds', examples=[31536000]
    )


class UserEmail(RootModel[str]):
    root: str = Field(
        ...,
        description="User's email (changing this resets the user's password and revokes existing tokens)",
        examples=['example@probely.com'],
    )


class UserId(RootModel[str]):
    root: str = Field(..., description="User's id", examples=['jMXUw-BE_2vd'])


class UserIsActive(RootModel[bool]):
    root: bool = Field(..., description='Deleted users are marked as not active')


class UserIsAdmin(RootModel[bool]):
    root: bool = Field(..., description='Account admin')


class UserIsBillingAdmin(RootModel[bool]):
    root: bool = Field(..., description='Billing contact for the account')


class UserName(RootModel[str]):
    root: str = Field(..., description="User's name", examples=['Henrique Cimento'])


class UserTitle(Enum):
    ceo = 'ceo'
    cto = 'cto'
    cso = 'cso'
    seceng = 'seceng'
    dev = 'dev'
    devop = 'devop'
    manager = 'manager'
    other = 'other'


class Username(RootModel[str]):
    root: str = Field(..., examples=['example@probely.com'])


class Vat(RootModel[str]):
    root: str = Field(..., description='Company VAT registration number')


class VerificationDate(RootModel[datetime]):
    root: datetime = Field(
        ...,
        description='Verification date time',
        examples=['2018-01-31T16:32:52.226652Z'],
    )


class VerificationLastError(RootModel[str]):
    root: str = Field(..., description='Reason for last verification failure.')


class VerificationMethod(Enum):
    dns = 'dns'
    file = 'file'


class VerificationToken(RootModel[str]):
    root: str = Field(
        ...,
        description='Token used to verify',
        examples=['a38351cb-ede8-4dc8-9366-80d3a7042d9a'],
    )


class VerificationType(Enum):
    dns = 'dns'
    file = 'file'


class Verified(RootModel[bool]):
    root: bool = Field(..., description='Has resource ownership been verified')


class WebhookApiVersion(Enum):
    v1 = 'v1'


class WebhookCheckCert(RootModel[bool]):
    root: bool = Field(..., description='Verify webhook URL HTTPS certificate')


class WebhookURL(RootModel[str]):
    root: str = Field(..., description='URL to post events to (must be https)')


class ZipCode(RootModel[str]):
    root: str = Field(..., description='Address ZIP code')


class AccountGetResponse(BaseModel):
    detail: Optional[str] = None


class AuthObtainPostResponse(BaseModel):
    token: Optional[Token] = None
    ttl: Optional[Ttl] = None


class AuthObtainPostResponse1(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class AuthObtainPostResponse2(BaseModel):
    detail: Optional[str] = None


class AuthRefreshPostRequest(BaseModel):
    token: Optional[TokenBody] = None


class AuthRefreshPostResponse(BaseModel):
    token: Optional[Token] = None
    ttl: Optional[Ttl] = None


class AuthRefreshPostResponse1(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class AuthRefreshPostResponse2(BaseModel):
    detail: Optional[str] = None


class AuthRevokePostRequest(BaseModel):
    token: Optional[TokenBody] = None


class AuthRevokePostResponse(BaseModel):
    token: Optional[Token] = None
    ttl: Optional[Ttl] = None


class AuthRevokePostResponse1(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class AuthRevokePostResponse2(BaseModel):
    detail: Optional[str] = None


class AuthVerifyPostRequest(BaseModel):
    token: Optional[TokenBody] = None


class AuthVerifyPostResponse(BaseModel):
    token: Optional[Token] = None
    ttl: Optional[Ttl] = None


class AuthVerifyPostResponse1(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class AuthVerifyPostResponse2(BaseModel):
    detail: Optional[str] = None


class BillingPatchResponse(BaseModel):
    detail: Optional[str] = None


class BillingPatchResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class BillingPutResponse(BaseModel):
    detail: Optional[str] = None


class BillingPutResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class BillingEstimatePostResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class BillingEstimatePostResponse1(BaseModel):
    detail: Optional[str] = None


class BillingEstimatePostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class BillingSubscribePostResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class BillingSubscribePostResponse1(BaseModel):
    detail: Optional[str] = None


class BillingSubscribePostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class CheckPostRequest(BaseModel):
    token: EmailToken


class CheckPostResponse(BaseModel):
    message: Optional[str] = Field(None, description='Message')


class CheckPostResponse1(BaseModel):
    error: Optional[str] = Field(None, description='Error message')


class EnterpriseAuthObtainPostResponse(BaseModel):
    token: Optional[Token] = None
    ttl: Optional[Ttl] = None


class EnterpriseAuthObtainPostResponse1(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class EnterpriseAuthObtainPostResponse2(BaseModel):
    detail: Optional[str] = None


class EnterpriseAuthRefreshPostRequest(BaseModel):
    token: Optional[TokenBody] = None


class EnterpriseAuthRefreshPostResponse(BaseModel):
    token: Optional[Token] = None
    ttl: Optional[Ttl] = None


class EnterpriseAuthRefreshPostResponse1(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class EnterpriseAuthRefreshPostResponse2(BaseModel):
    detail: Optional[str] = None


class EnterpriseAuthRevokePostRequest(BaseModel):
    token: Optional[TokenBody] = None


class EnterpriseAuthRevokePostResponse(BaseModel):
    token: Optional[Token] = None
    ttl: Optional[Ttl] = None


class EnterpriseAuthRevokePostResponse1(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class EnterpriseAuthRevokePostResponse2(BaseModel):
    detail: Optional[str] = None


class EnterpriseAuthVerifyPostRequest(BaseModel):
    token: Optional[TokenBody] = None


class EnterpriseAuthVerifyPostResponse(BaseModel):
    token: Optional[Token] = None
    ttl: Optional[Ttl] = None


class EnterpriseAuthVerifyPostResponse1(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class EnterpriseAuthVerifyPostResponse2(BaseModel):
    detail: Optional[str] = None


class EventsGetResponse1(BaseModel):
    detail: Optional[str] = None


class EventsGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class EventsIdGetResponse(BaseModel):
    detail: Optional[str] = None


class EventsIdGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class EventsIdGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class FrameworksGetResponse1(BaseModel):
    detail: Optional[str] = None


class FrameworksIdGetResponse(BaseModel):
    detail: Optional[str] = None


class FrameworksIdGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class IntegrationsGetResponse(BaseModel):
    detail: Optional[str] = None


class IntegrationsGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class IntegrationsJiraCloudProjectsGetResponse(RootModel[List[JiraProject]]):
    root: List[JiraProject]


class IntegrationsJiraCloudProjectsGetResponse1(BaseModel):
    detail: Optional[str] = None


class IntegrationsJiraCloudProjectsGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class IntegrationsJiraCloudProjectsProjectIdIssueTypesGetResponse(
    RootModel[List[JiraIssueType]]
):
    root: List[JiraIssueType]


class IntegrationsJiraCloudProjectsProjectIdIssueTypesGetResponse1(BaseModel):
    detail: Optional[str] = None


class IntegrationsJiraCloudProjectsProjectIdIssueTypesGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class IntegrationsJiraCloudProjectsProjectIdIssueTypesGetResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class IntegrationsJiraCloudProjectsProjectIdIssueTypesIssueTypeIdPrioritiesGetResponse(
    RootModel[List[JiraIssuePriority]]
):
    root: List[JiraIssuePriority]


class IntegrationsJiraCloudProjectsProjectIdIssueTypesIssueTypeIdPrioritiesGetResponse1(
    BaseModel
):
    detail: Optional[str] = None


class IntegrationsJiraCloudProjectsProjectIdIssueTypesIssueTypeIdPrioritiesGetResponse2(
    BaseModel
):
    detail: Optional[str] = Field(None, description='Error message.')


class IntegrationsJiraCloudProjectsProjectIdIssueTypesIssueTypeIdStatusGetResponse(
    RootModel[List[JiraIssueStatus]]
):
    root: List[JiraIssueStatus]


class IntegrationsJiraCloudProjectsProjectIdIssueTypesIssueTypeIdStatusGetResponse1(
    BaseModel
):
    detail: Optional[str] = None


class IntegrationsJiraCloudProjectsProjectIdIssueTypesIssueTypeIdStatusGetResponse2(
    BaseModel
):
    detail: Optional[str] = Field(None, description='Error message.')


class IntegrationsJiraCloudProjectsProjectIdIssueTypesIssueTypeIdStatusGetResponse3(
    BaseModel
):
    detail: Optional[str] = Field(None, description='Not found.')


class IntegrationsJiraServerProjectsGetResponse(RootModel[List[JiraProject]]):
    root: List[JiraProject]


class IntegrationsJiraServerProjectsGetResponse1(BaseModel):
    detail: Optional[str] = None


class IntegrationsJiraServerProjectsGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class IntegrationsJiraServerProjectsProjectIdIssueTypesGetResponse(
    RootModel[List[JiraIssueType]]
):
    root: List[JiraIssueType]


class IntegrationsJiraServerProjectsProjectIdIssueTypesGetResponse1(BaseModel):
    detail: Optional[str] = None


class IntegrationsJiraServerProjectsProjectIdIssueTypesGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class IntegrationsJiraServerProjectsProjectIdIssueTypesGetResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class IntegrationsJiraServerProjectsProjectIdIssueTypesIssueTypeIdPrioritiesGetResponse(
    RootModel[List[JiraIssuePriority]]
):
    root: List[JiraIssuePriority]


class IntegrationsJiraServerProjectsProjectIdIssueTypesIssueTypeIdPrioritiesGetResponse1(
    BaseModel
):
    detail: Optional[str] = None


class IntegrationsJiraServerProjectsProjectIdIssueTypesIssueTypeIdPrioritiesGetResponse2(
    BaseModel
):
    detail: Optional[str] = Field(None, description='Error message.')


class IntegrationsJiraServerProjectsProjectIdIssueTypesIssueTypeIdStatusGetResponse(
    RootModel[List[JiraIssueStatus]]
):
    root: List[JiraIssueStatus]


class IntegrationsJiraServerProjectsProjectIdIssueTypesIssueTypeIdStatusGetResponse1(
    BaseModel
):
    detail: Optional[str] = None


class IntegrationsJiraServerProjectsProjectIdIssueTypesIssueTypeIdStatusGetResponse2(
    BaseModel
):
    detail: Optional[str] = Field(None, description='Error message.')


class IntegrationsJiraServerProjectsProjectIdIssueTypesIssueTypeIdStatusGetResponse3(
    BaseModel
):
    detail: Optional[str] = Field(None, description='Not found.')


class KeysGetResponse1(BaseModel):
    detail: Optional[str] = None


class KeysGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class KeysPostResponse(BaseModel):
    detail: Optional[str] = None


class KeysPostResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class KeysIdDeleteResponse(BaseModel):
    detail: Optional[str] = None


class KeysIdDeleteResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class KeysIdGetResponse(BaseModel):
    detail: Optional[str] = None


class KeysIdGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class LabelsGetResponse1(BaseModel):
    detail: Optional[str] = None


class LabelsPostResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class LabelsPostResponse1(BaseModel):
    detail: Optional[str] = None


class LabelsIdDeleteResponse(BaseModel):
    detail: Optional[str] = None


class LabelsIdGetResponse(BaseModel):
    detail: Optional[str] = None


class LabelsIdGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class LabelsIdPatchResponse(BaseModel):
    detail: Optional[str] = None


class LabelsIdPatchResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class LabelsIdPutResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class LabelsIdPutResponse1(BaseModel):
    detail: Optional[str] = None


class LabelsIdPutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class ProfileChangePasswordPostRequest(BaseModel):
    confpassword: Password
    current_password: Password
    password: Password


class ProfileChangePasswordPostResponse(BaseModel):
    message: Optional[str] = Field(None, description='Message')


class ProfileChangePasswordPostResponse1(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class ProfileChangePasswordPostResponse2(BaseModel):
    detail: Optional[str] = None


class ResetPostRequest(BaseModel):
    email: Username


class ResetPostResponse(BaseModel):
    message: Optional[str] = Field(None, description='Message')


class ResetPostResponse1(BaseModel):
    error: Optional[str] = Field(None, description='Error message')


class SetpasswordPostRequest(BaseModel):
    confpassword: Password
    password: Password
    token: EmailToken


class SetpasswordPostResponse(BaseModel):
    message: Optional[str] = Field(None, description='Message')


class SetpasswordPostResponse1(BaseModel):
    error: Optional[str] = Field(None, description='Error message')


class TargetsGetResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsGetResponse3(BaseModel):
    detail: Optional[str] = None


class TargetsPostResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsPostResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsPostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsPostResponse3(BaseModel):
    detail: Optional[str] = None


class TargetsActivatePostResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsActivatePostResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsActivatePostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class Results(BaseModel):
    high: Optional[int] = Field(
        None,
        description='Average fix time in seconds for high severity findings',
        examples=[2],
    )
    low: Optional[int] = Field(
        None,
        description='Average fix time in seconds for low severity findings',
        examples=[3],
    )
    medium: Optional[int] = Field(
        None,
        description='Average fix time in seconds for medium severity findings',
        examples=[5],
    )


class TargetsAllAverageFixTimeGetResponse(BaseModel):
    results: Optional[Results] = None


class Field0(BaseModel):
    field_0: Optional[str] = Field(
        'needing attention', alias='0', description='needing attention'
    )
    field_1: Optional[int] = Field(None, alias='1', description='Number of targets')
    field_2: Optional[str] = Field(
        'needs_atention', alias='2', description='needs_atention'
    )


class Field1(BaseModel):
    field_0: Optional[str] = Field(
        'no issues found', alias='0', description='no issues found'
    )
    field_1: Optional[int] = Field(None, alias='1', description='Number of targets')
    field_2: Optional[str] = Field(
        'no_issues_found', alias='2', description='no_issues_found'
    )


class TargetsAllNeedsAttentionPieGetResponse(BaseModel):
    field_0: Optional[Field0] = Field(
        None,
        alias='0',
        description='These are arrays, they are being displayed as objects with numerical indexes due to limitations of the framework.\n',
    )
    field_1: Optional[Field1] = Field(
        None,
        alias='1',
        description='These are arrays, they are being displayed as objects with numerical indexes due to limitations of the framework.\n',
    )


class TargetsAllNeedsAttentionTopGetResponseItem(BaseModel):
    highs: Optional[int] = Field(
        None, description='Number of high severity findings', examples=[3]
    )
    id: Optional[str] = Field(None, description='Target id', examples=['QJxMvgPebu0e'])
    lows: Optional[int] = Field(
        None, description='Number of low severity findings', examples=[4]
    )
    mediums: Optional[int] = Field(
        None, description='Number of medium severity findings', examples=[8]
    )
    name: Optional[str] = Field(None, description='Name', examples=['Probely'])
    url: Optional[str] = Field(
        None, description="Target's site URL", examples=['https://probely.com']
    )


class TargetsAllNeedsAttentionTopGetResponse(
    RootModel[List[TargetsAllNeedsAttentionTopGetResponseItem]]
):
    root: List[TargetsAllNeedsAttentionTopGetResponseItem]


class TargetsAllRiskTrendGetResponseItem(BaseModel):
    field_0: Optional[datetime] = Field(None, alias='0', description='Date time')
    field_1: Optional[int] = Field(None, alias='1', description='Risk score')


class TargetsAllRiskTrendGetResponse(
    RootModel[List[TargetsAllRiskTrendGetResponseItem]]
):
    root: List[TargetsAllRiskTrendGetResponseItem]


class TargetsAllScansGetResponse1(BaseModel):
    detail: Optional[str] = None


class Started(RootModel[List[date]]):
    root: List[date]


class TargetsAllScheduledscansExpandedGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class HighItem(BaseModel):
    field_0: Optional[datetime] = Field(None, alias='0', description='Date time')
    field_1: Optional[int] = Field(None, alias='1', description='Risk score')


class LowItem(BaseModel):
    field_0: Optional[datetime] = Field(None, alias='0', description='Date time')
    field_1: Optional[int] = Field(None, alias='1', description='Risk score')


class MediumItem(BaseModel):
    field_0: Optional[datetime] = Field(None, alias='0', description='Date time')
    field_1: Optional[int] = Field(None, alias='1', description='Risk score')


class Results1(BaseModel):
    high: Optional[List[HighItem]] = None
    low: Optional[List[LowItem]] = None
    medium: Optional[List[MediumItem]] = None


class TargetsAllSeverityTrendGetResponse(BaseModel):
    results: Optional[Results1] = None
    step: Optional[float] = Field(None, description='', examples=[86400])


class TargetsAllTopVulnsGetResponseItem(BaseModel):
    field_0: Optional[str] = Field(None, alias='0', description='Vulnerability name')
    field_1: Optional[str] = Field(None, alias='1', description='Vulnerability count')


class TargetsAllTopVulnsGetResponse(RootModel[List[TargetsAllTopVulnsGetResponseItem]]):
    root: List[TargetsAllTopVulnsGetResponseItem]


class TargetsArchivePostResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsArchivePostResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsArchivePostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsArchivedPostResponse1(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsArchivedPostResponse2(BaseModel):
    detail: Optional[str] = None


class TargetsArchivedPostResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsIdDeleteResponse(BaseModel):
    detail: Optional[str] = None


class TargetsIdDeleteResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsIdDeleteResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsIdGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsIdGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsIdGetResponse2(BaseModel):
    detail: Optional[str] = None


class TargetsIdPatchResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsIdPatchResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsIdPatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsIdPatchResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsIdPutResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsIdPutResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsIdPutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsIdPutResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdAssetsGetResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdAssetsGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdAssetsPostResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdAssetsPostResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdAssetsPostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdAssetsPostResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdAssetsIdDeleteResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdAssetsIdDeleteResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdAssetsIdDeleteResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdAssetsIdGetResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdAssetsIdGetResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdAssetsIdGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdAssetsIdPatchResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdAssetsIdPatchResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdAssetsIdPatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdAssetsIdPatchResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdAssetsIdPutResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdAssetsIdPutResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdAssetsIdPutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdAssetsIdPutResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdAssetsIdVerifyPostRequest(BaseModel):
    type: VerificationType


class TargetsTargetIdAssetsIdVerifyPostResponse(BaseModel):
    message: Optional[str] = Field(None, description='Message')


class TargetsTargetIdAssetsIdVerifyPostResponse1(BaseModel):
    error: Optional[str] = Field(None, description='Error message')


class TargetsTargetIdAssetsIdVerifyPostResponse2(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdAssetsIdVerifyPostResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdAssetsIdVerifyPostResponse4(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class Results2(BaseModel):
    high: Optional[int] = Field(
        None,
        description='Average fix time in seconds for high severity findings',
        examples=[2],
    )
    low: Optional[int] = Field(
        None,
        description='Average fix time in seconds for low severity findings',
        examples=[3],
    )
    medium: Optional[int] = Field(
        None,
        description='Average fix time in seconds for medium severity findings',
        examples=[5],
    )


class TargetsTargetIdAverageFixTimeGetResponse(BaseModel):
    results: Optional[Results2] = None


class TargetsTargetIdEventsGetResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdEventsGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdEventsGetResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdEventsIdGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdEventsIdGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdEventsIdGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdFindingsGetResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class Scan1(RootModel[List[str]]):
    root: List[str]


class Assignee1(RootModel[List[str]]):
    root: List[str]


class Label1(RootModel[List[str]]):
    root: List[str]


class TargetsTargetIdFindingsBulkReportPostResponse(BaseModel):
    error: Optional[str] = Field(None, description='Error message')


class TargetsTargetIdFindingsBulkReportPostResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsBulkReportPostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdFindingsBulkRetestPostResponse(BaseModel):
    error: Optional[str] = Field(None, description='Error message')


class TargetsTargetIdFindingsBulkRetestPostResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsBulkRetestPostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdFindingsBulkUpdatePatchResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdFindingsBulkUpdatePatchResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsBulkUpdatePatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdFindingsReportGetResponse(BaseModel):
    error: Optional[str] = Field(None, description='Error message')


class TargetsTargetIdFindingsReportGetResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsReportGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdFindingsIdGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsIdGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdFindingsIdPatchResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdFindingsIdPatchResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsIdPatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdFindingsIdPatchResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdFindingsIdPutResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdFindingsIdPutResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsIdPutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdFindingsIdPutResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdFindingsIdIntegrationsJiraCloudGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsIdIntegrationsJiraCloudGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdFindingsIdIntegrationsJiraCloudPatchResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsIdIntegrationsJiraCloudPatchResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdFindingsIdIntegrationsJiraCloudPatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdFindingsIdIntegrationsJiraCloudPutResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsIdIntegrationsJiraCloudPutResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdFindingsIdIntegrationsJiraCloudPutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdFindingsIdIntegrationsJiraServerGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsIdIntegrationsJiraServerGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdFindingsIdIntegrationsJiraServerPatchResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsIdIntegrationsJiraServerPatchResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdFindingsIdIntegrationsJiraServerPatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdFindingsIdIntegrationsJiraServerPutResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsIdIntegrationsJiraServerPutResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdFindingsIdIntegrationsJiraServerPutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdFindingsIdLogGetResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsIdLogGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdFindingsIdRetestPostResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdFindingsIdRetestPostResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdFindingsIdRetestPostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdIntegrationsGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdIntegrationsGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdIntegrationsJiraCloudGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdIntegrationsJiraCloudGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdIntegrationsJiraCloudPatchResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdIntegrationsJiraCloudPatchResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdIntegrationsJiraCloudPatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdIntegrationsJiraCloudPutResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdIntegrationsJiraCloudPutResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdIntegrationsJiraCloudPutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdIntegrationsJiraServerGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdIntegrationsJiraServerGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdIntegrationsJiraServerPatchResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdIntegrationsJiraServerPatchResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdIntegrationsJiraServerPatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdIntegrationsJiraServerPutResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdIntegrationsJiraServerPutResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdIntegrationsJiraServerPutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdIntegrationsSlackGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdIntegrationsSlackGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdIntegrationsSlackPatchResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdIntegrationsSlackPatchResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdIntegrationsSlackPatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdIntegrationsSlackPutResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdIntegrationsSlackPutResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdIntegrationsSlackPutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdKeysGetResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdKeysGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdKeysPostResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdKeysPostResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdKeysPostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdKeysPostResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdKeysIdDeleteResponse(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdKeysIdDeleteResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdKeysIdGetResponse(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdKeysIdGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdRiskTrendGetResponseItem(BaseModel):
    field_0: Optional[datetime] = Field(None, alias='0', description='Date time')
    field_1: Optional[int] = Field(None, alias='1', description='Risk score')


class TargetsTargetIdRiskTrendGetResponse(
    RootModel[List[TargetsTargetIdRiskTrendGetResponseItem]]
):
    root: List[TargetsTargetIdRiskTrendGetResponseItem]


class TargetsTargetIdScanNowPostRequest(BaseModel):
    scan_profile: Optional[ScanProfile] = Field(
        'normal', description="Override the target's `scan_profile`.\n"
    )


class TargetsTargetIdScanNowPostResponse(BaseModel):
    error: Optional[str] = Field(None, description='Error message')


class TargetsTargetIdScanNowPostResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScanNowPostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdScanNowPostResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScansGetResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScansGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScansDatesGetResponse(RootModel[List[date]]):
    root: List[date] = Field(
        ...,
        description='Dates for which there are scans',
        examples=[['2017-06-12', '2017-06-22']],
    )


class TargetsTargetIdScansDatesGetResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScansDatesGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScansRetrievePageGetResponse(BaseModel):
    page: Optional[int] = Field(None, description='Page number')


class TargetsTargetIdScansRetrievePageGetResponse1(BaseModel):
    error: Optional[str] = Field(None, description='Error message')


class TargetsTargetIdScansRetrievePageGetResponse2(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScansRetrievePageGetResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScansIdGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScansIdGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScansIdCancelPostResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScansIdCancelPostResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdScansIdCancelPostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScansIdEndpointsGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScansIdEndpointsGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScansIdReportGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScansIdReportGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScansIdReportDefaultGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScansIdReportDefaultGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScansIdReportOwaspGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScansIdReportOwaspGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScansIdReportPciGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScansIdReportPciGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScheduledscansGetResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScheduledscansGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScheduledscansPostRequest(BaseModel):
    date_time: ScanDateTime
    recurrence: Optional[Recurrence] = None


class TargetsTargetIdScheduledscansPostResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdScheduledscansPostResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScheduledscansPostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdScheduledscansPostResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScheduledscansExpandedGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScheduledscansIdDeleteResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScheduledscansIdDeleteResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdScheduledscansIdGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScheduledscansIdGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScheduledscansIdPatchRequest(BaseModel):
    date_time: ScanDateTime
    recurrence: Optional[Recurrence] = None


class TargetsTargetIdScheduledscansIdPatchResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdScheduledscansIdPatchResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScheduledscansIdPatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdScheduledscansIdPatchResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdScheduledscansIdPutRequest(BaseModel):
    date_time: ScanDateTime
    recurrence: Optional[Recurrence] = None


class TargetsTargetIdScheduledscansIdPutResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdScheduledscansIdPutResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdScheduledscansIdPutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdScheduledscansIdPutResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class Results3(BaseModel):
    high: Optional[List[HighItem]] = None
    low: Optional[List[LowItem]] = None
    medium: Optional[List[MediumItem]] = None


class TargetsTargetIdSeverityTrendGetResponse(BaseModel):
    results: Optional[Results3] = None
    step: Optional[float] = Field(None, description='', examples=[86400])


class TargetsTargetIdSiteGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdSiteGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdSitePatchResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdSitePatchResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdSitePatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdSitePatchResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdSitePutResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdSitePutResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdSitePutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdSitePutResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdSiteVerifyPostRequest(BaseModel):
    type: VerificationType


class TargetsTargetIdSiteVerifyPostResponse(BaseModel):
    message: Optional[str] = Field(None, description='Message')


class TargetsTargetIdSiteVerifyPostResponse1(BaseModel):
    error: Optional[str] = Field(None, description='Error message')


class TargetsTargetIdSiteVerifyPostResponse2(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdSiteVerifyPostResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdSiteVerifyPostResponse4(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdTopVulnsGetResponseItem(BaseModel):
    field_0: Optional[str] = Field(None, alias='0', description='Vulnerability name')
    field_1: Optional[str] = Field(None, alias='1', description='Vulnerability count')


class TargetsTargetIdTopVulnsGetResponse(
    RootModel[List[TargetsTargetIdTopVulnsGetResponseItem]]
):
    root: List[TargetsTargetIdTopVulnsGetResponseItem]


class TargetsTargetIdWebhooksGetResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdWebhooksGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdWebhooksPostResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdWebhooksPostResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdWebhooksPostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdWebhooksPostResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdWebhooksIdDeleteResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdWebhooksIdDeleteResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdWebhooksIdDeleteResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdWebhooksIdGetResponse(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdWebhooksIdGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdWebhooksIdPatchResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdWebhooksIdPatchResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdWebhooksIdPatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdWebhooksIdPatchResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class TargetsTargetIdWebhooksIdPutResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class TargetsTargetIdWebhooksIdPutResponse1(BaseModel):
    detail: Optional[str] = None


class TargetsTargetIdWebhooksIdPutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class TargetsTargetIdWebhooksIdPutResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class UsersGetResponse1(BaseModel):
    detail: Optional[str] = None


class UsersPostRequest(BaseModel):
    email: UserEmail
    is_admin: Optional[UserIsAdmin] = None
    name: UserName
    title: Optional[UserTitle] = None


class UsersIdDeleteResponse(BaseModel):
    detail: Optional[str] = None


class UsersIdDeleteResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class UsersIdDeleteResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class UsersIdGetResponse(BaseModel):
    detail: Optional[str] = None


class UsersIdGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class UsersIdPatchRequest(BaseModel):
    email: UserEmail
    is_admin: Optional[UserIsAdmin] = None
    name: UserName
    title: Optional[UserTitle] = None


class UsersIdPatchResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class UsersIdPatchResponse1(BaseModel):
    detail: Optional[str] = None


class UsersIdPatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class UsersIdPatchResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class UsersIdPutRequest(BaseModel):
    email: UserEmail
    is_admin: Optional[UserIsAdmin] = None
    name: UserName
    title: Optional[UserTitle] = None


class UsersIdPutResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class UsersIdPutResponse1(BaseModel):
    detail: Optional[str] = None


class UsersIdPutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class UsersIdPutResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class VulnerabilityDefinitionsGetResponse1(BaseModel):
    detail: Optional[str] = None


class VulnerabilityDefinitionsIdGetResponse(BaseModel):
    detail: Optional[str] = None


class WebhooksGetResponse1(BaseModel):
    detail: Optional[str] = None


class WebhooksGetResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class WebhooksPostResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class WebhooksPostResponse1(BaseModel):
    detail: Optional[str] = None


class WebhooksPostResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class WebhooksPostResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class WebhooksIdDeleteResponse(BaseModel):
    detail: Optional[str] = None


class WebhooksIdDeleteResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class WebhooksIdDeleteResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class WebhooksIdGetResponse(BaseModel):
    detail: Optional[str] = None


class WebhooksIdGetResponse1(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class WebhooksIdPatchResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class WebhooksIdPatchResponse1(BaseModel):
    detail: Optional[str] = None


class WebhooksIdPatchResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class WebhooksIdPatchResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class WebhooksIdPutResponse(BaseModel):
    field_field_name_: Optional[List[str]] = Field(None, alias='<field name>')
    non_field_errors: Optional[List[str]] = None


class WebhooksIdPutResponse1(BaseModel):
    detail: Optional[str] = None


class WebhooksIdPutResponse2(BaseModel):
    detail: Optional[str] = Field(None, description='Error message.')


class WebhooksIdPutResponse3(BaseModel):
    detail: Optional[str] = Field(None, description='Not found.')


class APIKey(BaseModel):
    id: Optional[Id] = None
    key: Optional[Token] = None
    name: Optional[Name] = ''


class Assignee(BaseModel):
    email: Optional[UserEmail] = None
    id: Optional[UserId] = None
    name: Optional[UserName] = None


class BasicAuth(BaseModel):
    password: Optional[Password] = None
    username: Optional[BasicAuthUsername] = None


class Billing(BaseModel):
    address: Address
    city: City
    country: Country
    email: Email
    first_name: FirstName
    last_name: LastName
    other: Optional[str] = Field(None, description='Extra data')
    reg_number: Optional[RegistrationNumber] = None
    vat_number: Vat
    zip: ZipCode


class ChangedBy(BaseModel):
    email: Optional[UserEmail] = None
    id: Optional[UserId] = None
    name: Optional[UserName] = None


class CreatedBy(BaseModel):
    email: Optional[UserEmail] = None
    id: Optional[UserId] = None
    name: Optional[UserName] = None


class FindingBulkRetest(FindingBulkIds):
    scan_profile: Optional[ScanProfile] = 'normal'


class Framework(BaseModel):
    desc: Optional[str] = Field(None, description='Framework description')
    id: Optional[Id] = None
    name: Optional[Id] = None


class Invoice(BaseModel):
    amount_due: Optional[int] = Field(
        None, description='Amount remaining to pay in cents'
    )
    amount_paid: Optional[int] = Field(None, description='Amount already paid in cents')
    currency_code: Optional[CurrencyCode] = None
    discounts: Optional[List[Discount]] = None
    line_items: Optional[List[LineItem]] = None
    plan: Optional[str] = Field(None, description='Plan name')
    plan_id: Optional[AccountPlanId] = None
    sub_total: Optional[int] = Field(None, description='Price before taxes in cents')
    taxes: Optional[List[Tax]] = None
    total: Optional[int] = Field(None, description='Price after taxes in cents')


class JiraFinding(BaseModel):
    issue_id: Optional[JiraIssueId] = None
    selective_sync: Optional[JiraSelectiveSync] = None


class JiraScope(BaseModel):
    allow_jira: Optional[JiraAllowJira] = None
    auto_sync: Optional[JiraAutoSync] = None
    issue_type_id: Optional[JiraIssueTypeId] = None
    priority_mapping: Optional[JiraPriorityMapping] = None
    project_id: Optional[JiraProjectId] = None
    status_mapping: Optional[JiraStatusMapping] = None


class Key(BaseModel):
    id: Optional[Id] = None
    key: Optional[Token] = None
    name: Optional[Id] = None


class Label(BaseModel):
    id: Optional[Id] = None
    name: Optional[Name] = ''


class Login(BaseModel):
    password: Password
    username: Username


class Plan(BaseModel):
    allowed_scan_profiles: Optional[PlanAllowedScanProfiles] = None
    charge_model: Optional[PlanChargeModel] = None
    currency_code: Optional[CurrencyCode] = None
    description: Optional[Desc] = ''
    id: Optional[Id] = None
    is_trial: Optional[PlanIsTrial] = None
    name: Optional[Name] = ''
    period: Optional[BillingPeriod] = None
    period_unit: Optional[BillingPeriodUnit] = None
    price: Optional[Price] = None


class Reporter(BaseModel):
    email: Optional[UserEmail] = None
    id: Optional[UserId] = None
    name: Optional[UserName] = None


class Stack(RootModel[List[FrameworkNames]]):
    root: List[FrameworkNames] = Field(
        ..., description='List of frameworks detected on this resource'
    )


class Subscription(BaseModel):
    coupon_ids: Optional[Coupons] = None
    plan_id: Optional[AccountPlanId] = None
    target_ids: Optional[TargetIds] = None


class AllowedScanProfile(BaseModel):
    id: Optional[ScanProfile] = 'normal'
    name: Optional[str] = Field(None, description='Name of the scan profile.')


class TargetSimple(BaseModel):
    desc: Optional[Desc] = ''
    id: Optional[Id] = None
    name: Optional[Name] = ''
    stack: Optional[Stack] = None
    url: Optional[str] = Field(None, description="Target's site URL")


class User(BaseModel):
    changed: Optional[Changed] = None
    changed_by: Optional[ChangedBy] = None
    email: Optional[UserEmail] = None
    id: Optional[Id] = None
    is_active: Optional[UserIsActive] = None
    is_admin: Optional[UserIsAdmin] = None
    is_billing_admin: Optional[UserIsBillingAdmin] = None
    name: Optional[UserName] = None
    title: Optional[UserTitle] = None


class VulnerabilityDefinition(BaseModel):
    changed: Optional[Changed] = None
    desc: Optional[Desc] = ''
    id: Optional[Id] = None
    name: Optional[Name] = ''


class Webhook(BaseModel):
    api_version: Optional[WebhookApiVersion] = None
    changed: Optional[Changed] = None
    changed_by: Optional[ChangedBy] = None
    check_cert: Optional[WebhookCheckCert] = None
    created: Optional[Changed] = None
    created_by: Optional[ChangedBy] = None
    id: Optional[Id] = None
    name: Optional[Name] = ''
    url: WebhookURL


class WebhookList(RootModel[List[Webhook]]):
    root: List[Webhook]


class FrameworksGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[Framework]] = Field(None, description='Framework objects')


class KeysGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[Key]] = Field(None, description='API key objects')


class LabelsGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[Label]] = Field(None, description='label objects.')


class PlansGetResponse(RootModel[List[Plan]]):
    root: List[Plan]


class TargetsTargetIdKeysGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[Key]] = Field(None, description='API key objects')


class TargetsTargetIdWebhooksGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[Webhook]] = Field(None, description='Webhook objects')


class UsersGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[User]] = Field(None, description='User objects')


class VulnerabilityDefinitionsGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[VulnerabilityDefinition]] = Field(
        None, description='Vulnerability definition objects.'
    )


class WebhooksGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[Webhook]] = Field(None, description='Webhook objects')


class Account(BaseModel):
    auto_collection: Optional[AccountAutoCollection] = None
    balance: Optional[AccountBalance] = None
    balance_currency_code: Optional[CurrencyCode] = None
    free_target_quantity: Optional[FreeTargetQuantity] = None
    has_used_trial: Optional[HasUsedTrial] = None
    heroku: Optional[bool] = Field(None, description='Heroku accounts (for future use)')
    next_billing_at: Optional[AccountNextBillingAt] = None
    plan: Optional[Plan] = None
    plan_target_quantity: Optional[PlanTargetQuantity] = None
    pool_size: Optional[PoolSize] = None
    status: Optional[AccountStatus] = None
    trialEnd: Optional[TrialEnd] = None


class Activity(BaseModel):
    change: Optional[Change] = Field(
        None,
        description='Type of change:\n  * created - First time the issue is found\n  * comment - User left a comment in the timeline\n  * found - Found again in a later scan\n  * changed - One of the parameters of the finding was changed\n   (e.g. severity)\n',
    )
    changed: Optional[Changed] = None
    changed_by: Optional[ChangedBy] = None
    field: Optional[str] = Field(None, description='Field that was changed')
    old_value: Optional[str] = Field(None, description='Previous value')
    value: Optional[str] = Field(None, description='New value')


class Asset(BaseModel):
    changed: Optional[Changed] = None
    changed_by: Optional[ChangedBy] = None
    cookies: Optional[Cookies] = None
    desc: Optional[Desc] = ''
    headers: Optional[Headers] = None
    host: Optional[Host] = None
    id: Optional[Id] = None
    include: Optional[Include] = None
    name: Optional[Name] = ''
    stack: Optional[Stack] = None
    verification_date: Optional[VerificationDate] = None
    verification_last_error: Optional[VerificationLastError] = None
    verification_method: Optional[VerificationMethod] = None
    verification_token: Optional[VerificationToken] = None
    verified: Optional[Verified] = False


class Finding(BaseModel):
    assignee: Optional[Assignee] = None
    changed: Optional[Changed] = None
    changed_by: Optional[ChangedBy] = None
    comment: Optional[str] = Field(
        None, description='User comment left on the finding.'
    )
    cvss_score: Optional[FindingCVSSScore] = None
    cvss_vector: Optional[FindingCVSSVector] = None
    definition: Optional[Definition] = None
    evidence: Optional[str] = Field(None, description='Evidence for the finding.')
    extra: Optional[str] = Field(None, description='Extra data for the finding.')
    fix: Optional[str] = Field(
        None, description='Fix sugestion for the vulnerability and framework'
    )
    id: Optional[Id] = None
    insertion_point: Optional[FindingInsertionPoint] = None
    labels: Optional[List[str]] = Field(
        None, description='User labels for the finding.'
    )
    last_found: Optional[datetime] = Field(
        None,
        description='Date time of the last time the vulnerability was found.',
        examples=['2018-02-19T18:58:50.906015Z'],
    )
    method: Optional[Method] = None
    parameter: Optional[str] = Field(None, description='Vulnerable paramenter.')
    params: Optional[str] = Field(None, description='Request parameters')
    path: Optional[str] = Field(None, description='Finding path.')
    reporter: Optional[Reporter] = None
    requests: Optional[Requests] = None
    scans: Optional[List[str]] = Field(
        None, description='Scan ids where this finding was present.'
    )
    severity: Optional[FindingSeverity] = None
    state: Optional[FindingState] = None
    target: Optional[TargetSimple] = None
    url: Optional[str] = Field(None, description='Full finding URL')
    value: Optional[str] = Field(None, description='Value for parameter.')


class FindingUpdate(BaseModel):
    assignee: Optional[Assignee] = None
    changed: Optional[Changed] = None
    changed_by: Optional[ChangedBy] = None
    comment: Optional[str] = Field(
        None, description='User comment left on the finding.'
    )
    cvss_score: Optional[FindingCVSSScore] = None
    cvss_vector: Optional[FindingCVSSVector] = None
    definition: Optional[Definition] = None
    evidence: Optional[str] = Field(None, description='Evidence for the finding.')
    extra: Optional[str] = Field(None, description='Extra data for the finding.')
    fix: Optional[str] = Field(
        None, description='Fix sugestion for the vulnerability and framework'
    )
    id: Optional[Id] = None
    insertion_point: Optional[FindingInsertionPoint] = None
    labels: Optional[List[str]] = Field(
        None, description='User labels for the finding.'
    )
    last_found: Optional[datetime] = Field(
        None,
        description='Date time of the last time the vulnerability was found.',
        examples=['2018-02-19T18:58:50.906015Z'],
    )
    method: Optional[Method] = None
    parameter: Optional[str] = Field(None, description='Vulnerable paramenter.')
    params: Optional[str] = Field(None, description='Request parameters')
    path: Optional[str] = Field(None, description='Finding path.')
    reporter: Optional[Reporter] = None
    requests: Optional[Requests] = None
    scans: Optional[List[str]] = Field(
        None, description='Scan ids where this finding was present.'
    )
    severity: Optional[FindingSeverity] = None
    state: Optional[FindingState] = None
    target: Optional[TargetSimple] = None
    url: Optional[str] = Field(None, description='Full finding URL')
    value: Optional[str] = Field(None, description='Value for parameter.')


class Scan(BaseModel):
    changed: Optional[Changed] = None
    changed_by: Optional[ChangedBy] = None
    completed: Optional[ScanCompleted] = None
    crawler: Optional[Crawler] = Field(
        None,
        description='Information on the status of the crawling step of the scanning process',
    )
    created: Optional[Created] = None
    created_by: Optional[CreatedBy] = None
    fingerprinter: Optional[Fingerprinter] = Field(
        None,
        description='Information on the status of the crawling step of the scanning process',
    )
    highs: Optional[int] = Field(
        None, description='Number of high severity findings in this scan'
    )
    id: Optional[Id] = None
    lows: Optional[int] = Field(
        None, description='Number of low severity findings in this scan'
    )
    mediums: Optional[int] = Field(
        None, description='Number of medium severity findings in this scan'
    )
    scan_profile: Optional[ScanProfile] = 'normal'
    scanner: Optional[Scanner] = Field(
        None,
        description='Information on the status of the search for vulnerabilities of the scanning process',
    )
    started: Optional[ScanStarted] = None
    status: Optional[ScanStatus] = None
    target: Optional[TargetSimple] = None


class Scheduled(BaseModel):
    changed: Optional[Changed] = None
    changed_by: Optional[ChangedBy] = None
    date_time: Optional[ScanDateTime] = None
    id: Optional[str] = Field(
        None, description='Scheduled object id', examples=['QJxMvgPebu0e']
    )
    recurrence: Optional[Recurrence] = None
    target: Optional[TargetSimple] = None


class Site(BaseModel):
    basic_auth: Optional[BasicAuth] = None
    changed: Optional[Changed] = None
    changed_by: Optional[ChangedBy] = None
    cookies: Optional[Cookies] = None
    desc: Optional[Desc] = ''
    form_login: Optional[FormLogin] = None
    form_login_check_pattern: Optional[FormLoginCheckPattern] = ''
    form_login_url: Optional[FormLoginUrl] = ''
    has_basic_auth: Optional[HasBasicAuth] = False
    has_form_login: Optional[HasFormLogin] = False
    headers: Optional[Headers] = None
    host: Optional[SiteHost] = ''
    id: Optional[Id] = None
    name: Optional[Name] = ''
    stack: Optional[Stack] = None
    url: Optional[SiteUrl] = ''
    verification_date: Optional[VerificationDate] = None
    verification_last_error: Optional[VerificationLastError] = None
    verification_method: Optional[VerificationMethod] = None
    verification_token: Optional[VerificationToken] = None
    verified: Optional[Verified] = False
    whitelist: Optional[Whitelist] = None


class Target(BaseModel):
    allowed_scan_profiles: Optional[List[AllowedScanProfile]] = Field(
        None, description='Valid scan profiles for the target.'
    )
    assets: Optional[List[Asset]] = Field(
        None, description='Secondary domains that should be scanned'
    )
    changed: Optional[Changed] = None
    changed_by: Optional[ChangedBy] = None
    connected_target: Optional[ConnectedTarget] = None
    enabled: Optional[Enabled] = None
    environment: Optional[Environment] = 'testing'
    id: Optional[Id] = None
    labels: Optional[List[str]] = Field(
        None,
        description='User labels for the scope. (This feature is currently only available for certain accounts,\nplease contact our support if you are interested in using it)\n',
    )
    name: Optional[Name] = ''
    report_type: Optional[ReportType] = None
    scan_profile: Optional[ScanProfile] = 'normal'
    site: Optional[Site] = None
    type: Optional[TargetType] = 'single'


class TargetsGetResponse(BaseModel):
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    pagination_count: Optional[PaginationCount] = None
    results: Optional[List[Target]] = Field(None, description='Target objects')


class TargetsAllScansGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[Scan]] = Field(None, description='Scan objects')


class TargetsAllScheduledscansExpandedGetResponse(BaseModel):
    results: Optional[List[Scheduled]] = Field(
        None, description='Scheduled scan objects'
    )


class TargetsArchivedPostResponse(BaseModel):
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    pagination_count: Optional[PaginationCount] = None
    results: Optional[List[Target]] = Field(None, description='Target objects')


class TargetsTargetIdAssetsGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[Asset]] = Field(None, description='Asset objects.')


class TargetsTargetIdFindingsGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[Finding]] = Field(None, description='Finding objects.')


class TargetsTargetIdFindingsIdLogGetResponse(RootModel[List[Activity]]):
    root: List[Activity]


class TargetsTargetIdScansGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[Scan]] = Field(None, description='Scan objects')


class TargetsTargetIdScheduledscansGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[Scheduled]] = Field(
        None, description='Scheduled scan objects'
    )


class TargetsTargetIdScheduledscansExpandedGetResponse(BaseModel):
    results: Optional[List[Scheduled]] = Field(
        None, description='Scheduled scan objects'
    )


class EventContent(RootModel[Union[User, Target, Scan, Finding]]):
    root: Union[User, Target, Scan, Finding] = Field(..., description='Event object.')


class FindingBulkUpdate(FindingBulkIds, FindingUpdate):
    pass


class Event(BaseModel):
    content: Optional[EventContent] = None
    event_type: Optional[EventType] = None
    id: Optional[Id] = None
    object_type: Optional[EventObjectType] = None
    ocurred_at: Optional[EventOccurredAt] = None
    webhooks: Optional[WebhookList] = None


class EventsGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[Event]] = Field(None, description='Event objects')


class TargetsTargetIdEventsGetResponse(BaseModel):
    count: Optional[PaginationCount] = None
    length: Optional[PaginationLength] = Field(
        default_factory=lambda: PaginationLength.model_validate(10)
    )
    page: Optional[PaginationPage] = Field(
        default_factory=lambda: PaginationPage.model_validate(1)
    )
    page_total: Optional[PaginationPageTotal] = None
    results: Optional[List[Event]] = Field(None, description='Event objects')
